/* tf_psa_crypto_config_check_before.h: checks before including the user configuration file. */
/* Automatically generated by generate_config_checks.py. Do not edit! */

#if !defined(TF_PSA_CRYPTO_CONFIG_CHECK_ALLOW_REMOVED_OPTIONS)

#define TF_PSA_CRYPTO_CONFIG_CHECK_option_is_no_longer_supported 0xdeadc0f1

/* *INDENT-OFF* */

#if defined(MBEDTLS_USE_PSA_CRYPTO)
#  define TF_PSA_CRYPTO_CONFIG_CHECK_defined_MBEDTLS_USE_PSA_CRYPTO 1
#  undef MBEDTLS_USE_PSA_CRYPTO
#else
#  define TF_PSA_CRYPTO_CONFIG_CHECK_defined_MBEDTLS_USE_PSA_CRYPTO 0
#endif
#define MBEDTLS_USE_PSA_CRYPTO TF_PSA_CRYPTO_CONFIG_CHECK_option_is_no_longer_supported

/* *INDENT-ON* */

#endif /* !defined(TF_PSA_CRYPTO_CONFIG_CHECK_ALLOW_REMOVED_OPTIONS) */

/* End of automatically generated tf_psa_crypto_config_check_before.h */
